swagger: '2.0'

info:
  version: "1.0.0"
  title: Muscle Camp

paths:
  /users:
  
    post:
      description: |
        ユーザ登録

      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              icon:
                type: string
                format: byte
                example: ""
              identity:
                type: string
                example: kinnniku
              introduction:
                type: string
                example: 自己紹介
              name:
                type: string
                example: 筋肉マン
              password:
                type: string
                format: password
                example: password

      responses:
        200:
          description: ユーザ登録成否
          schema:
            type: object
            properties:
              result:
                type: boolean
                example: true
                
  /users/{id}:
  
    get:
      description: |
        ユーザ情報取得

      parameters:
        - name: id
          in: path
          description: ユーザ名
          required: true
          type: string
                
      responses:
        200:
          description: Successful responses
          schema:
            type: object
            properties:
              icon:
                type: string
                format: byte
                example: ""
              identity:
                type: string
                example: kinnniku
              introduction:
                type: string
                example: 自己紹介
              name:
                type: string
                example: 筋肉マン
    post:
      description: |
        ユーザ情報編集
      
      parameters:
        - name: id
          in: path
          description: ユーザ名
          required: true
          type: string
          
        - name: user
          in: body
          schema:
            type: object
            properties:
              icon:
                type: string
                format: byte
                example: ""
              identity:
                type: string
                example: kinnniku
              introduction:
                type: string
                example: 自己紹介
              name:
                type: string
                example: 筋肉マン
              password:
                type: string
                format: password
                example: password
                
      responses:
        200:
          description: Successful responses
          
    delete:
      description: ユーザ削除
      parameters:
        - name: id
          in: path
          description: ユーザ名
          required: true
          type: string
          
      responses:
        200:
          description: ユーザ削除成否
          schema:
            type: object
            properties:
              result:
                type: boolean
                example: true
                
  /muscle_posts:
    get:
      description: 投稿取得(タイムライン用)
      
      parameters:
        - name: limit
          type: integer
          in: query
          description: 投稿取得数上限
          required: true
                
      responses:
        200:
          description: Successful responses
          schema:
            type: object
            properties:
              muscle_posts:
                type: array
                items:
                  type: object
                  properties:
                    icon:
                      type: string
                      format: byte
                      example: ""
                    identity:
                      type: string
                      example: kinnniku
                    name:
                      type: string
                      example: 筋肉マン
                    title:
                      type: string
                      example: 腕立て
                    body:
                      type: string
                      example: 腕立て千回
                    body_parts:
                      type: array
                      items:
                        type: string
                        example: 腕
                
    post:
      description: 投稿
      
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              identity:
                type: string
                example: kinnniku
              title:
                type: string
                example: 腕立て
              body:
                type: string
                example: 腕立て千回
              body_parts:
                type: array
                items:
                  type: string
                  example: 腕
                
      responses:
          200:
            description: Successful responses
          
  /mucle_posts/{id}:
  
    get:
      description: 投稿取得
      
      parameters:
        - name: id
          in: path
          description: 投稿id
          required: true
          type: integer
          format: int32
                
      responses:
        200:
          description: Successful responses
          schema:
            type: object
            properties:
              icon:
                type: string
                format: byte
                example: ""
              identity:
                type: string
                example: kinnniku
              name:
                type: string
                example: 筋肉マン
              title:
                type: string
                example: 腕立て
              body:
                type: string
                example: 腕立て千回
              body_parts:
                type: array
                items:
                  type: string
                  example: 腕
        
    post:
      description: 投稿編集
      
      parameters:
        - name: id
          in: path
          description: 投稿id
          required: true
          type: integer
          format: int32
          
        - name: body
          in: body
          schema:
            type: object
            properties:
              identity:
                type: string
                example: kinnniku
              title:
                type: string
                example: 腕立て
              body:
                type: string
                example: 腕立て千回
              body_parts:
                type: array
                items:
                  type: string
                  example: 腕
                  
      responses:
        200:
          description: 投稿編集成否
          schema:
            type: object
            properties:
              result:
                type: boolean
                example: true
  
    
    

    